#!/bin/bash
set -euo pipefail

# Log shutdown reason and kill all child processes on exit
_shutdown() {
    local reason="${1:-unknown}"
    echo "PIPELINE SHUTDOWN: $reason at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >&2
    kill 0
}
trap '_shutdown "EXIT (set -e or normal)"' EXIT
trap '_shutdown "SIGINT (ctrl-c)"' INT
trap '_shutdown "SIGTERM (killed)"' TERM
trap '_shutdown "SIGHUP (terminal closed)"' HUP

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_DIR"

source lib/config.sh
source lib/state.sh
source lib/scoring.sh
source lib/logging.sh
source lib/progress.sh
source lib/audit.sh

# ── Prerequisites ──────────────────────────────────────────────

for cmd in claude yq jq python3; do
    if ! command -v "$cmd" &>/dev/null; then
        echo "FATAL: Required command not found: $cmd" >&2
        exit 1
    fi
done

if [[ ! -f "premise.md" ]]; then
    echo "FATAL: premise.md not found. Create it with your story premise." >&2
    exit 1
fi

for required in auditor-config.yaml criteria-definitions.yaml; do
    if [[ ! -f "$required" ]]; then
        echo "FATAL: $required not found." >&2
        exit 1
    fi
done

# Load criteria settings if they exist (generated by process_questionnaire.py)
if [[ -f "criteria-settings.yaml" ]]; then
    load_criteria_settings "criteria-settings.yaml"
else
    echo "WARNING: criteria-settings.yaml not found. All criteria enabled by default." >&2
fi

init_state
init_logging
init_progress
if [[ -f "model-settings.yaml" ]]; then
    load_model_settings "model-settings.yaml"
fi
mkdir -p output

PREMISE_FILE="output/synthesized-premise.md"
BRAINSTORM_BATCH_SIZE=5
PIPELINE_LOG=""

# Log to both stderr and the pipeline log file
pipelog() {
    echo "$*" >&2
    if [[ -n "$PIPELINE_LOG" ]]; then
        echo "$*" >> "$PIPELINE_LOG"
    fi
}

# ── Helpers ────────────────────────────────────────────────────

count_chapters() {
    grep -c '^## Chapter [0-9]' output/novel-plan.md
}

count_scenes() {
    local plan_file="$1"
    grep -c '^## Scene [0-9]' "$plan_file"
}

extract_scene_plan() {
    local plan_file="$1"
    local scene_num="$2"
    python3 -c "
import re, sys
text = open(sys.argv[1]).read()
pattern = r'(## Scene ' + sys.argv[2] + r':.*?)(?=## Scene \d+:|$)'
match = re.search(pattern, text, re.DOTALL)
if match:
    print(match.group(1).strip())
else:
    print(f'FATAL: Scene {sys.argv[2]} not found in {sys.argv[1]}', file=sys.stderr)
    sys.exit(1)
" "$plan_file" "$scene_num"
}

extract_chapter_description() {
    local plan_file="$1"
    local ch_num="$2"
    python3 -c "
import re, sys
text = open(sys.argv[1]).read()
pattern = r'(## Chapter ' + sys.argv[2] + r':.*?)(?=## Chapter \d+:|$)'
match = re.search(pattern, text, re.DOTALL)
if match:
    print(match.group(1).strip())
else:
    print(f'FATAL: Chapter {sys.argv[2]} not found in {sys.argv[1]}', file=sys.stderr)
    sys.exit(1)
" "$plan_file" "$ch_num"
}

build_completed_summary() {
    local up_to_ch="$1"
    for ((c=1; c<=up_to_ch; c++)); do
        local dir
        dir=$(printf "output/chapters/%02d" "$c")
        if [[ -d "$dir" && -f "$dir/chapter-plan.md" ]]; then
            printf '\n## Chapter %d (COMPLETED)\n' "$c"
            cat "$dir/chapter-plan.md"
        fi
    done
}

build_preceding_scenes() {
    local ch_dir="$1"
    local up_to_scene="$2"
    for ((s=1; s<up_to_scene; s++)); do
        local sf="$ch_dir/scene-$(printf '%02d' "$s").md"
        if [[ -f "$sf" ]]; then
            printf '\n\n--- Scene %d ---\n' "$s"
            cat "$sf"
        fi
    done
}

build_all_completed_prose() {
    local up_to_ch="$1"
    for ((c=1; c<up_to_ch; c++)); do
        local dir
        dir=$(printf "output/chapters/%02d" "$c")
        for sf in "$dir"/scene-*.md; do
            [[ -f "$sf" ]] && cat "$sf" && echo ""
        done
    done
}

# Run claude and write output to a file (not stdout).
# Args: $1 = prompt text, $2 = description, $3 = output file path
run_claude_write() {
    local prompt="$1"
    local desc="${2:-unnamed}"
    local outfile="$3"
    local model_flag="${4:-}"
    run_claude_to_file "$desc" "$prompt" "$outfile" "$model_flag"
}

# ── Phase 0: Premise Brainstorming ────────────────────────────

phase_premise_brainstorm() {
    if marker_done "phase-premise-brainstorm"; then
        echo "Premise brainstorming already done, skipping." >&2
        return
    fi

    echo "=== Phase 0: Premise Brainstorming ===" >&2
    update_state "phase" '"premise_brainstorming"'

    mkdir -p output/brainstorm/premise

    # Generate ideation guidance
    python3 generate_ideation_guidance.py premise > "$STATE_DIR/ideation-guidance-premise.txt"

    # Launch ideation agents ONLY for ideas that don't exist yet
    local total=10
    local needed=0
    local needed_ids=()

    for ((i=1; i<=total; i++)); do
        local idx
        idx=$(printf '%02d' "$i")
        local idea_file="output/brainstorm/premise/idea-${idx}.md"
        if [[ -f "$idea_file" && -s "$idea_file" ]]; then
            echo "  Idea $i already exists ($(wc -c < "$idea_file") bytes), skipping." >&2
        else
            needed=$((needed + 1))
            needed_ids+=("$i")
        fi
    done

    if [[ "$needed" -gt 0 ]]; then
        echo "Generating $needed missing premise ideas..." >&2

        local batch_count=0
        for i in "${needed_ids[@]}"; do
            (
                idx=$(printf '%02d' "$i")
                step_id="ideate-premise-$idx"
                idea_dir="$LOG_DIR/$step_id"
                mkdir -p "$idea_dir"

                step_start "$step_id" "Premise ideation agent $i"

                words=$(python3 random_words.py 5 | tr '\n' ', ' | sed 's/, $//')
                prompt=$(python3 fill_template.py prompts/ideate-premise.md \
                    "premise=premise.md" \
                    "random_words=$words" \
                    "ideation_guidance=$STATE_DIR/ideation-guidance-premise.txt")

                local idea_file="output/brainstorm/premise/idea-${idx}.md"
                local write_prompt="${prompt}

---
IMPORTANT: Write your complete output to the file: ${idea_file}
Use the Write tool to create this file. Do not output your response as text — write it to the file.
Do not write any other files. Do not use any other tools."

                echo "$write_prompt" > "$idea_dir/prompt.md"
                step_heartbeat "$step_id"

                echo "$write_prompt" | claude -p - \
                    --tools "Read,Write" \
                    --dangerously-skip-permissions \
                    $(get_model_flag ideation) \
                    --output-format text \
                    > "$idea_dir/claude-stdout.txt" 2>&1

                if [[ -f "$idea_file" && -s "$idea_file" ]]; then
                    cp "$idea_file" "$idea_dir/response.md"
                    step_done "$step_id" "$(wc -c < "$idea_file") bytes"
                else
                    step_failed "$step_id" "output file not written"
                fi
            ) &

            batch_count=$((batch_count + 1))
            if (( batch_count % BRAINSTORM_BATCH_SIZE == 0 )); then
                wait
            fi
        done
        wait
    fi

    # Verify all ideas exist and have content
    local idea_count=0
    for ((i=1; i<=total; i++)); do
        local idx
        idx=$(printf '%02d' "$i")
        local idea_file="output/brainstorm/premise/idea-${idx}.md"
        if [[ -f "$idea_file" && -s "$idea_file" ]]; then
            idea_count=$((idea_count + 1))
        else
            echo "WARNING: idea-${idx}.md missing or empty after generation" >&2
        fi
    done
    echo "$idea_count of $total premise ideas ready." >&2

    # Concatenate all ideas
    cat output/brainstorm/premise/idea-*.md > "$STATE_DIR/all-premise-ideas.txt"

    # Synthesize
    echo "Synthesizing premise..." >&2
    local assembled
    assembled=$(python3 fill_template.py prompts/synthesize-premise.md \
        "premise=premise.md" \
        "candidate_ideas=$STATE_DIR/all-premise-ideas.txt")
    run_claude_write "$assembled" "synthesize-premise" "$PREMISE_FILE" "$(get_model_flag synthesis)"

    echo "Synthesized premise written to $PREMISE_FILE" >&2
    marker_set "phase-premise-brainstorm"
}

# ── Phase 1: Novel Planning ───────────────────────────────────

phase_novel_planning() {
    if marker_done "phase-novel-plan-audit"; then
        echo "Novel plan already done, skipping." >&2
        return
    fi

    echo "=== Phase 1: Novel Planning ===" >&2
    update_state "phase" '"novel_planning"'

    if ! marker_done "phase-novel-plan-written"; then
        echo "Creating novel plan..." >&2
        local assembled
        assembled=$(python3 fill_template.py prompts/plan-novel.md \
            "premise=$PREMISE_FILE")
        run_claude_write "$assembled" "plan-novel" "output/novel-plan.md" "$(get_model_flag planning)"
        marker_set "phase-novel-plan-written"
    fi

    echo "Auditing novel plan..." >&2
    local no_chapters_file="$STATE_DIR/no-chapters-yet.txt"
    echo "(No chapters written yet)" > "$no_chapters_file"
    audit_refine_loop "novel_plan" "output/novel-plan.md" \
        "prompts/fix-novel-plan.md" "novel-plan" \
        "premise=$PREMISE_FILE" \
        "synthesized_premise=$PREMISE_FILE" \
        "novel_plan=output/novel-plan.md" \
        "completed_chapters_summary=$no_chapters_file"
    marker_set "phase-novel-plan-audit"

    echo "Novel plan complete." >&2
}

# ── Phase 2: Chapter Brainstorming ────────────────────────────

phase_chapter_brainstorm() {
    local ch="$1"
    local ch_dir="$2"
    local ch_pad
    ch_pad=$(printf '%02d' "$ch")
    local concept_file="$ch_dir/chapter-concept.md"

    if marker_done "ch-${ch_pad}-concept"; then
        echo "  Chapter $ch concept already done, skipping." >&2
        return
    fi

    echo "  Brainstorming chapter $ch concepts..." >&2

    mkdir -p "output/brainstorm/chapters/$(printf '%02d' "$ch")"
    local brainstorm_dir="output/brainstorm/chapters/$(printf '%02d' "$ch")"

    # Extract chapter description from novel plan
    local ch_desc_file="$STATE_DIR/chapter-description.txt"
    extract_chapter_description "output/novel-plan.md" "$ch" > "$ch_desc_file"

    # Build completed chapters summary
    local summary_file="$STATE_DIR/completed-summary-bs.txt"
    if [[ "$ch" -gt 1 ]]; then
        build_completed_summary "$((ch - 1))" > "$summary_file"
    else
        echo "(No prior chapters)" > "$summary_file"
    fi

    # Generate ideation guidance
    python3 generate_ideation_guidance.py chapter > "$STATE_DIR/ideation-guidance-chapter.txt"

    # Launch ideation agents ONLY for ideas that don't exist yet
    local total=5
    local needed_ids=()

    for ((i=1; i<=total; i++)); do
        local idx
        idx=$(printf '%02d' "$i")
        local idea_file="$brainstorm_dir/idea-${idx}.md"
        if [[ -f "$idea_file" && -s "$idea_file" ]]; then
            echo "    Chapter $ch idea $i already exists, skipping." >&2
        else
            needed_ids+=("$i")
        fi
    done

    if [[ "${#needed_ids[@]}" -gt 0 ]]; then
        echo "    Generating ${#needed_ids[@]} missing chapter ideas..." >&2
        for i in "${needed_ids[@]}"; do
            (
                idx=$(printf '%02d' "$i")
                step_id="ideate-chapter-$(printf '%02d' "$ch")-$idx"
                idea_log_dir="$LOG_DIR/$step_id"
                mkdir -p "$idea_log_dir"

                step_start "$step_id" "Chapter $ch ideation agent $i"

                words=$(python3 random_words.py 5 | tr '\n' ', ' | sed 's/, $//')
                prompt=$(python3 fill_template.py prompts/ideate-chapter.md \
                    "synthesized_premise=$PREMISE_FILE" \
                    "novel_plan=output/novel-plan.md" \
                    "chapter_description=$ch_desc_file" \
                    "completed_chapters_summary=$summary_file" \
                    "random_words=$words")

                local idea_file="$brainstorm_dir/idea-${idx}.md"
                local write_prompt="${prompt}

---
IMPORTANT: Write your complete output to the file: ${idea_file}
Use the Write tool to create this file. Do not output your response as text — write it to the file.
Do not write any other files. Do not use any other tools."

                echo "$write_prompt" > "$idea_log_dir/prompt.md"
                step_heartbeat "$step_id"

                echo "$write_prompt" | claude -p - \
                    --tools "Read,Write" \
                    --dangerously-skip-permissions \
                    $(get_model_flag ideation) \
                    --output-format text \
                    > "$idea_log_dir/claude-stdout.txt" 2>&1

                if [[ -f "$idea_file" && -s "$idea_file" ]]; then
                    cp "$idea_file" "$idea_log_dir/response.md"
                    step_done "$step_id" "$(wc -c < "$idea_file") bytes"
                else
                    step_failed "$step_id" "output file not written"
                fi
            ) &
        done
        wait
    fi

    # Concatenate all approaches
    cat "$brainstorm_dir"/idea-*.md > "$STATE_DIR/all-chapter-ideas.txt"

    # Synthesize
    echo "  Synthesizing chapter $ch concept..." >&2
    local assembled
    assembled=$(python3 fill_template.py prompts/synthesize-chapter.md \
        "synthesized_premise=$PREMISE_FILE" \
        "novel_plan=output/novel-plan.md" \
        "chapter_description=$ch_desc_file" \
        "completed_chapters_summary=$summary_file" \
        "candidate_approaches=$STATE_DIR/all-chapter-ideas.txt")
    run_claude_write "$assembled" "synthesize-chapter-$ch" "$concept_file" "$(get_model_flag synthesis)"
    marker_set "ch-${ch_pad}-concept"
}

# ── Phase 2+3: Chapter Planning + Scene Authoring ─────────────

process_chapters() {
    local chapter_count
    chapter_count=$(count_chapters)

    # Iterate all chapters from 1; each step self-skips via markers
    for ((ch=1; ch<=chapter_count; ch++)); do
        echo "=== Chapter $ch of $chapter_count ===" >&2
        update_state "chapter" "$ch"

        local ch_dir
        ch_dir=$(printf "output/chapters/%02d" "$ch")
        mkdir -p "$ch_dir"

        # Brainstorm chapter concept
        phase_chapter_brainstorm "$ch" "$ch_dir"

        # Plan chapter
        plan_one_chapter "$ch" "$ch_dir"

        # Author scenes
        author_chapter_scenes "$ch" "$ch_dir"

        # Backtrack: re-evaluate novel plan after chapter completion
        run_backtrack_novel "$ch"

        # Re-count chapters in case backtracking added/removed some
        chapter_count=$(count_chapters)

        # Reset scene counter for next chapter
        update_state "scene" "0"
    done
}

plan_one_chapter() {
    local ch="$1"
    local ch_dir="$2"
    local ch_pad
    ch_pad=$(printf '%02d' "$ch")
    local plan_file="$ch_dir/chapter-plan.md"

    if marker_done "ch-${ch_pad}-plan-audit"; then
        echo "  Chapter $ch plan already done, skipping." >&2
        return
    fi

    update_state "phase" '"chapter_planning"'
    update_state "scene" "0"

    if ! marker_done "ch-${ch_pad}-plan-written"; then
        echo "  Planning chapter $ch..." >&2

        local summary_file="$STATE_DIR/completed-summary.txt"
        if [[ "$ch" -gt 1 ]]; then
            build_completed_summary "$((ch - 1))" > "$summary_file"
        else
            echo "(No prior chapters)" > "$summary_file"
        fi

        local assembled
        assembled=$(python3 fill_template.py prompts/plan-chapter.md \
            "premise=$PREMISE_FILE" \
            "synthesized_premise=$PREMISE_FILE" \
            "novel_plan=output/novel-plan.md" \
            "chapter_number=$ch" \
            "chapter_concept=$ch_dir/chapter-concept.md" \
            "completed_chapters_summary=$summary_file")
        run_claude_write "$assembled" "plan-chapter-$ch" "$plan_file" "$(get_model_flag planning)"
        marker_set "ch-${ch_pad}-plan-written"
    fi

    echo "  Auditing chapter $ch plan..." >&2
    local no_scenes_file="$STATE_DIR/no-scenes-yet.txt"
    echo "(No scenes written yet)" > "$no_scenes_file"
    audit_refine_loop "chapter_plan" "$plan_file" \
        "prompts/fix-chapter-plan.md" "ch${ch_pad}-plan" \
        "premise=$PREMISE_FILE" \
        "synthesized_premise=$PREMISE_FILE" \
        "novel_plan=output/novel-plan.md" \
        "chapter_plan=$plan_file" \
        "completed_scenes=$no_scenes_file"
    marker_set "ch-${ch_pad}-plan-audit"
}

author_chapter_scenes() {
    local ch="$1"
    local ch_dir="$2"
    local ch_pad
    ch_pad=$(printf '%02d' "$ch")
    local plan_file="$ch_dir/chapter-plan.md"

    update_state "phase" '"scene_authoring"'

    local scene_count
    scene_count=$(count_scenes "$plan_file")

    # Iterate all scenes from 1; each sub-step self-skips via markers
    for ((sc=1; sc<=scene_count; sc++)); do
        local sc_pad
        sc_pad=$(printf '%02d' "$sc")
        local mk="ch-${ch_pad}-sc-${sc_pad}"

        echo "  Scene $sc of $scene_count" >&2
        update_state "scene" "$sc"

        local scene_file="$ch_dir/scene-${sc_pad}.md"
        local context_file="$ch_dir/scene-${sc_pad}-context.md"

        # Sub-step: collect context
        if ! marker_done "${mk}-context"; then
            collect_scene_context "$ch" "$sc" "$ch_dir" "$context_file" "$plan_file"
            marker_set "${mk}-context"
        fi

        # Build preceding scenes within this chapter (transient, not a sub-step)
        local preceding_file="$STATE_DIR/preceding-scenes.txt"
        build_preceding_scenes "$ch_dir" "$sc" > "$preceding_file"

        # Extract this scene's plan (transient)
        local scene_plan_file="$STATE_DIR/scene-plan.txt"
        extract_scene_plan "$plan_file" "$sc" > "$scene_plan_file"

        # Sub-step: author scene
        if ! marker_done "${mk}-written"; then
            echo "    Writing scene $sc..." >&2
            local assembled
            assembled=$(python3 fill_template.py prompts/author-scene.md \
                "premise=$PREMISE_FILE" \
                "synthesized_premise=$PREMISE_FILE" \
                "novel_plan=output/novel-plan.md" \
                "chapter_plan=$plan_file" \
                "relevant_context=$context_file" \
                "preceding_scenes=$preceding_file" \
                "scene_plan=$scene_plan_file" \
                "chapter_number=$ch" \
                "scene_number=$sc")
            run_claude_write "$assembled" "author-scene-ch${ch}-sc${sc}" "$scene_file" "$(get_model_flag planning)"
            marker_set "${mk}-written"
        fi

        # Sub-step: audit/refine scene
        if ! marker_done "${mk}-audit"; then
            echo "    Auditing scene $sc..." >&2
            local audit_result=0
            audit_refine_loop "scene" "$scene_file" \
                "prompts/fix-scene.md" "ch${ch_pad}-scene-${sc_pad}" \
                "premise=$PREMISE_FILE" \
                "synthesized_premise=$PREMISE_FILE" \
                "novel_plan=output/novel-plan.md" \
                "chapter_plan=$plan_file" \
                "relevant_context=$context_file" \
                "preceding_scenes=$preceding_file" \
                "scene=$scene_file" || audit_result=$?

            if [[ "$audit_result" -eq 2 ]]; then
                echo "    Scene $sc: fixer recommended deletion" >&2
                rm -f "$scene_file" "$context_file"
                marker_clear "${mk}-context"
                marker_clear "${mk}-written"
                run_backtrack_chapter "$ch" "$sc" "$ch_dir"
                marker_set "${mk}-ch-backtrack"
                scene_count=$(count_scenes "$plan_file")
                continue
            fi
            marker_set "${mk}-audit"
        fi

        # Sub-step: backtrack chapter plan after this scene
        if ! marker_done "${mk}-ch-backtrack"; then
            run_backtrack_chapter "$ch" "$sc" "$ch_dir"
            marker_set "${mk}-ch-backtrack"
        fi

        scene_count=$(count_scenes "$plan_file")
    done
}

collect_scene_context() {
    local ch="$1"
    local sc="$2"
    local ch_dir="$3"
    local output_file="$4"
    local plan_file="$5"

    if [[ "$ch" -le 1 ]]; then
        echo "# No prior chapters — this is Chapter 1" > "$output_file"
        return
    fi

    echo "    Collecting context for scene $sc..." >&2

    local prose_file="$STATE_DIR/all-completed-prose.txt"
    build_all_completed_prose "$ch" > "$prose_file"

    local scene_plan_file="$STATE_DIR/upcoming-scene-plan.txt"
    extract_scene_plan "$plan_file" "$sc" > "$scene_plan_file"

    local assembled
    assembled=$(python3 fill_template.py prompts/collect-context.md \
        "novel_plan=output/novel-plan.md" \
        "chapter_plan=$plan_file" \
        "upcoming_scene_plan=$scene_plan_file" \
        "completed_content=$prose_file")
    run_claude_write "$assembled" "collect-context-ch${ch}-sc${sc}" "$output_file" "$(get_model_flag context_collection)"
}

run_backtrack_chapter() {
    local ch="$1"
    local sc="$2"
    local ch_dir="$3"
    local ch_pad
    ch_pad=$(printf '%02d' "$ch")
    local sc_pad
    sc_pad=$(printf '%02d' "$sc")
    local mk="ch-${ch_pad}-sc-${sc_pad}"

    # Per-scene bt_output so it's unambiguous which scene this corresponds to
    local bt_output="$STATE_DIR/backtrack-chapter-${ch_pad}-sc-${sc_pad}.md"
    local scenes_file="$STATE_DIR/completed-scenes-bt.txt"

    # Build completed scenes
    local has_scenes=false
    > "$scenes_file"
    for sf in "$ch_dir"/scene-*.md; do
        [[ -f "$sf" ]] && cat "$sf" >> "$scenes_file" && echo "" >> "$scenes_file" && has_scenes=true
    done

    if [[ "$has_scenes" == "false" ]]; then
        return
    fi

    # Sub-step: evaluate backtracking (one-shot, marker-gated)
    if ! marker_done "${mk}-ch-backtrack-eval"; then
        echo "  Backtracking: evaluating chapter plan after scene $sc..." >&2
        rm -f "$bt_output"
        local assembled
        assembled=$(python3 fill_template.py prompts/backtrack-chapter.md \
            "premise=$PREMISE_FILE" \
            "synthesized_premise=$PREMISE_FILE" \
            "novel_plan=output/novel-plan.md" \
            "chapter_plan=$ch_dir/chapter-plan.md" \
            "completed_scenes=$scenes_file")
        run_claude_write "$assembled" "backtrack-chapter-${ch}-sc-${sc}" "$bt_output" "$(get_model_flag backtracking)"
        marker_set "${mk}-ch-backtrack-eval"
    fi

    # If NO_CHANGE or empty, no revision needed
    if [[ ! -s "$bt_output" ]] || head -1 "$bt_output" | grep -q "^NO_CHANGE"; then
        return
    fi

    # Sub-step: apply revision (idempotent cp)
    if ! marker_done "${mk}-ch-backtrack-applied"; then
        echo "  Chapter plan revised by backtracking" >&2
        cp "$bt_output" "$ch_dir/chapter-plan.md"
        marker_set "${mk}-ch-backtrack-applied"
    fi

    # Sub-step: audit the revised plan
    if ! marker_done "${mk}-ch-backtrack-audit"; then
        BACKTRACK_MODE=1 audit_refine_loop "chapter_plan" "$ch_dir/chapter-plan.md" \
            "prompts/fix-chapter-plan.md" "ch${ch_pad}-sc-${sc_pad}-plan-bt" \
            "premise=$PREMISE_FILE" \
            "synthesized_premise=$PREMISE_FILE" \
            "novel_plan=output/novel-plan.md" \
            "chapter_plan=$ch_dir/chapter-plan.md" \
            "completed_scenes=$scenes_file"
        marker_set "${mk}-ch-backtrack-audit"
    fi
}

run_backtrack_novel() {
    local ch="$1"
    local ch_pad
    ch_pad=$(printf '%02d' "$ch")
    local mk="ch-${ch_pad}"

    local bt_output="$STATE_DIR/backtrack-novel-${ch_pad}.md"
    local summary_file="$STATE_DIR/completed-summary-bt.txt"

    build_completed_summary "$ch" > "$summary_file"

    # Sub-step: evaluate backtracking
    if ! marker_done "${mk}-novel-backtrack-eval"; then
        echo "Backtracking: evaluating novel plan after chapter $ch..." >&2
        rm -f "$bt_output"
        local assembled
        assembled=$(python3 fill_template.py prompts/backtrack-novel.md \
            "premise=$PREMISE_FILE" \
            "synthesized_premise=$PREMISE_FILE" \
            "novel_plan=output/novel-plan.md" \
            "completed_chapters_summary=$summary_file")
        run_claude_write "$assembled" "backtrack-novel-after-ch$ch" "$bt_output" "$(get_model_flag backtracking)"
        marker_set "${mk}-novel-backtrack-eval"
    fi

    # If NO_CHANGE or empty, no revision needed
    if [[ ! -s "$bt_output" ]] || head -1 "$bt_output" | grep -q "^NO_CHANGE"; then
        return
    fi

    # Sub-step: apply revision
    if ! marker_done "${mk}-novel-backtrack-applied"; then
        echo "Novel plan revised by backtracking" >&2
        cp "$bt_output" output/novel-plan.md
        marker_set "${mk}-novel-backtrack-applied"
    fi

    # Sub-step: audit the revised plan
    if ! marker_done "${mk}-novel-backtrack-audit"; then
        BACKTRACK_MODE=1 audit_refine_loop "novel_plan" "output/novel-plan.md" \
            "prompts/fix-novel-plan.md" "novel-plan-bt-ch${ch_pad}" \
            "premise=$PREMISE_FILE" \
            "synthesized_premise=$PREMISE_FILE" \
            "novel_plan=output/novel-plan.md" \
            "completed_chapters_summary=$summary_file"
        marker_set "${mk}-novel-backtrack-audit"
    fi
}

# ── Main ───────────────────────────────────────────────────────

main() {
    PIPELINE_LOG="$STATE_DIR/pipeline-$(date -u +%Y%m%d-%H%M%S).log"

    echo "Fiction Pipeline starting at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >&2
    echo "Project dir: $PROJECT_DIR" >&2
    echo "Log dir: $LOG_DIR" >&2
    echo "Pipeline log: $PIPELINE_LOG" >&2

    local current_phase
    current_phase=$(read_state "phase")

    case "$current_phase" in
        premise_brainstorming|starting|null)
            phase_premise_brainstorm
            phase_novel_planning
            process_chapters
            ;;
        novel_planning)
            phase_premise_brainstorm  # Ensure premise exists
            phase_novel_planning
            process_chapters
            ;;
        chapter_planning|chapter_brainstorming|scene_authoring)
            phase_premise_brainstorm  # Ensure premise exists
            process_chapters
            ;;
        *)
            echo "FATAL: Unknown phase: $current_phase" >&2
            exit 1
            ;;
    esac

    echo "=== Pipeline complete at $(date -u +"%Y-%m-%dT%H:%M:%SZ") ===" >&2
}

main "$@"
